version: '3.7'

services:
  surging.test.server:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      Environment: ${ENVIRONMENT:-Development}
      ForceDisplayStackTrace: ${FORCED_DISPLAY_STACKTRACE:-false}
      SwaggerTitle: "surging.test.server"
      SwaggerDes: "服务提供者接口API文档"
      SupportName: "liuhongliang"
      SupportEmail: "1029765111@qq.com"
    ports:
      - "8080:8080"
  surging.test.client:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      ForceDisplayStackTrace: ${FORCED_DISPLAY_STACKTRACE:-false}
      SwaggerTitle: "surging.test.client"
      SwaggerDes: "服务调用者API文档"
      SupportName: "liuhongliang"
      SupportEmail: "1029765111@qq.com"
    ports:
      - "8081:8080"